version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ./run.sh
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

